"""Render an idea run as markdown concept cards.

Cards are the product; the walk trail is the audit record. Both are printed,
but the cards lead.
"""

from __future__ import annotations

from datetime import datetime, timezone

from rhizome.ideas.models import IdeaCard, IdeaRun


def render_cards(run: IdeaRun) -> str:
    """Render the full run as a markdown document.

    Args:
        run: A completed IdeaRun.

    Returns:
        Markdown string with concept cards, then the traversal trail.
    """
    lines: list[str] = []
    lines.append(f"# Ideas: {run.seed}\n")
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    kept = run.kept_cards()
    lines.append(
        f"*{stamp} | {len(run.walks)} walk(s), {len(run.cards)} concept(s), "
        f"{len(kept)} kept*\n"
    )

    if run.brief:
        lines.append("## Brief\n")
        lines.append(f"{run.brief}\n")

    ordered = sorted(run.cards, key=lambda c: c.confidence, reverse=True)
    if ordered:
        lines.append("## Concepts\n")
        for index, card in enumerate(ordered, start=1):
            lines.extend(_render_card(index, card))

    if run.summary:
        lines.append("## Assessment\n")
        lines.append(f"{run.summary}\n")

    lines.append("## Traversal trail\n")
    for walk in run.walks:
        lines.append(
            f"**Walk {walk.walk_id}** — seed: *{walk.plan.seed}* "
            f"(depth={walk.plan.depth}, epsilon={walk.plan.epsilon}, "
            f"temperature={walk.plan.temperature}, top_k={walk.plan.top_k}, "
            f"jumps={walk.jumps})\n"
        )
        if walk.plan.rationale:
            lines.append(f"> Intent: {walk.plan.rationale}\n")
        if walk.note:
            lines.append(f"> Assessment: {walk.note}\n")
        if not walk.fragments:
            lines.append("*no fragments returned*\n")
            continue
        for fragment in walk.fragments:
            jump_marker = " ⟂ JUMP" if fragment.forced_jump else ""
            lines.append(
                f"- `{fragment.chunk_id}` — [{fragment.article_title}]({fragment.article_url}) "
                f"(sim {fragment.similarity:.3f}, step {fragment.depth}{jump_marker})"
            )
        lines.append("")

    lines.append("---\n")
    lines.append("*Generated by rhizome idea agent — traversal + LLM synthesis*\n")
    return "\n".join(lines)


def _render_card(index: int, card: IdeaCard) -> list[str]:
    lines: list[str] = []
    flags = []
    flags.append(f"verdict: {card.verdict}")
    if card.is_tracing():
        flags.append(f"⚠ tracing of: {card.tracing_of}")
    if card.novelty.verdict:
        flags.append(f"novelty: {card.novelty.verdict} ({card.novelty.max_similarity:.2f})")
    if card.contested():
        flags.append("⚠ contested")
    flags.append(f"confidence: {card.confidence:.2f}")
    lines.append(f"### {index}. {card.name}\n")
    lines.append(f"*{' | '.join(flags)}*\n")
    if card.confidence_note:
        lines.append(f"*{card.confidence_note}*\n")
    lines.append(f"{card.statement}\n")

    if card.composition:
        lines.append(f"**Composition.** {card.composition}\n")

    if card.components:
        lines.append("**Components.**\n")
        for component in card.components:
            if component.register == "corpus":
                source = f"[{component.article_title}]({component.article_url})"
                lines.append(
                    f"- *(corpus)* {component.claim} — {source}, "
                    f"sim {component.similarity:.3f}, chunk `{component.chunk_id}`"
                )
                if component.quote:
                    lines.append(f"  > {component.quote}")
            else:
                audit = f" [{component.audit}]" if component.audit else ""
                lines.append(f"- *(model{audit})* {component.claim}")
                if component.audit_note:
                    lines.append(f"  - audit: {component.audit_note}")
        lines.append("")

    if card.stakes:
        lines.append(f"**Stakes.** {card.stakes}\n")
    if card.objection:
        lines.append(f"**Objection.** {card.objection}\n")
    if card.novelty.nearest_title:
        lines.append(
            f"**Nearest corpus text.** [{card.novelty.nearest_title}]"
            f"({card.novelty.nearest_url}) at {card.novelty.max_similarity:.3f}\n"
        )
    if card.walk_ids:
        lines.append(f"*material from walk(s): {', '.join(str(w) for w in card.walk_ids)}*\n")
    return lines
